services:
  - type: web
    name: qcs-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PORT
        value: 3306
      - key: CORS_ORIGIN
        value: https://ticudean.com